#!/usr/bin/env bash
# _______  _______  ______  _______  __        
#|       ||   _   ||   __ \|     __||  |.-----.
#|   -  _||       ||      <|__     ||  ||  _  |
#|_______||___|___||___|__||_______||__||   __|
#                                       |__|   
# QARSlp Qtile + Arch Ricing System
# By: gibranlp <thisdoesnotwork@gibranlp.dev>
# MIT licence 
# 

cp -R ~/QARSlp/dotfiles/shortc.conf ~/
sudo cp -R ~/QARSlp/scripts/. /opt/bin
sudo cp -R ~/QARSlp/widgets/. /opt/bin
