#!/usr/bin/env bash
# _______  _______  ______  _______  __        
#|       ||   _   ||   __ \|     __||  |.-----.
#|   -  _||       ||      <|__     ||  ||  _  |
#|_______||___|___||___|__||_______||__||   __|
#                                       |__|   
# QARSlp Qtile + Arch Ricing Script
# by: gibranlp <thisdoesnotwork@gibranlp.dev>
# MIT licence 
# 
rofi_command="rofi -theme ~/.config/rofi/chwall.rasi"

# Options
ten="10 minutes"
thi="30 minutes"
hou="60 minutes"
nin="90 minutes"
clear="Clear"

options="$ten\n$thi\n$hou\n$nin\n$clear"

chosen="$(echo -e "$options" | $rofi_command -p 'Change wallpaper every:' -dmenu -selected-row 0)"
case $chosen in
    $ten)
		sleep 1; watch -n 600 /opt/bin/genwal
		;;
    $thi)
		sleep 1; watch -n 1800 /opt/bin/genwal
		;;
    $hou)
		sleep 1; watch -n 3600 /opt/bin/genwal
        ;;
	$nin)
		sleep 1; watch -n 5400 /opt/bin/genwal
        ;;
	$clear)
		sleep 1; killall watch
        ;;
esac

