#!/usr/bin/env bash
# _______  _______  ______  _______  __        
#|       ||   _   ||   __ \|     __||  |.-----.
#|   -  _||       ||      <|__     ||  ||  _  |
#|_______||___|___||___|__||_______||__||   __|
#                                       |__|   
# QARSlp Qtile + Arch Ricing Script
# by: gibranlp <thisdoesnotwork@gibranlp.dev>
# MIT licence 
# 
rofi_command="rofi -theme ~/.config/rofi/logout.rasi"

# Options
lout=" Log Out"
rboot=" Reboot"
poff=" Poweroff"

options="$lout\n$rboot\n$poff"

chosen="$(echo -e "$options" | $rofi_command -p 'Session' -dmenu -selected-row 2)"
case $chosen in
    $lout)
		sleep 1; qtile cmd-obj -o cmd -f shutdown
		;;
    $rboot)
		sleep 1; sudo reboot
		;;
    $poff)
		sleep 1; sudo poweroff
        ;;
esac

