#!/usr/bin/env bash
# _______  _______  ______  _______  __        
#|       ||   _   ||   __ \|     __||  |.-----.
#|   -  _||       ||      <|__     ||  ||  _  |
#|_______||___|___||___|__||_______||__||   __|
#                                       |__|   
# QARSlp Qtile + Arch Ricing Script
# by: gibranlp <thisdoesnotwork@gibranlp.dev>
# MIT licence 
# 
rofi_command="rofi -theme ~/.config/rofi/theme.rasi"

## options
B1="Wal"
B3="Colorz"
B4="Colorthief"
B2="Haishoku"
B5="Wal light"
B6="Haishoku light"
B7="Colorz light"
B8="Colorthief light"

options="<- Dark ->\n$B1\n$B2\n$B3\n$B4\n<- Ligth ->\n$B5\n$B6\n$B7\n$B8"

## Main
chosen="$(echo -e "$options" | $rofi_command -p "Color Theme" -dmenu -selected-row 1)"
case $chosen in
    $B1)
		  /opt/bin/rldwal wal
        ;;
    $B2)
		  /opt/bin/rldwal haishoku
        ;;
    $B3)
		  /opt/bin/rldwal colorz
        ;;
    $B4)
		  /opt/bin/rldwal colorthief
        ;;
    $B5)
		  /opt/bin/rldwalw wal
        ;;
    $B6)
		  /opt/bin/rldwalw haishoku
        ;;
    $B7)
		  /opt/bin/rldwalw colorz
        ;;
    $B8)
		  /opt/bin/rldwalw colorthief
        ;;
esac

