#!/usr/bin/env bash
# _______  _______  ______  _______  __        
#|       ||   _   ||   __ \|     __||  |.-----.
#|   -  _||       ||      <|__     ||  ||  _  |
#|_______||___|___||___|__||_______||__||   __|
#                                       |__|   
# QARSlp Qtile + Arch Ricing Script
# by: gibranlp <thisdoesnotwork@gibranlp.dev>
# MIT licence 
#
rofi_command="rofi -theme ~/.config/rofi/left_toolbar.rasi"

# Options
wal="wal"
hai="haishoku"
col="colorz"
cth="colorthief"
wal_l="wal light"
hai_l="haishoku light"
col_l="colorz light"
cth_l="colorthief light"

options="<<-<< Dark >>->>\n$wal\n$hai\n$col\n$cth\n<<-<< Ligth >>->>\n$wal_l\n$hai_l\n$col_l\n$cth_l"

chosen="$(echo -e "$options" | $rofi_command -p '   Color Scheme' -dmenu -selected-row 1)"
case $chosen in
    $wal)
		/opt/bin/genwal -r -t $wal 
        ;;
    $hai)
		/opt/bin/genwal -r -t $hai
        ;;
    $col)
		/opt/bin/genwal -r -t $col
        ;;
    $cth)
		/opt/bin/genwal -r -t $cht
        ;;
    $wal_l)
		/opt/bin/genwal -r -t $wal -l
        ;;
    $hai_l)
		/opt/bin/genwal -r -t $hai -l
        ;;
    $col_l)
		/opt/bin/genwal -r -t $col -l
        ;;
    $cth_l)sh
		/opt/bin/genwal -r -t $cht -l
        ;;
esac
