#!/usr/bin/env bash
# _______  _______  ______  _______  __        
#|       ||   _   ||   __ \|     __||  |.-----.
#|   -  _||       ||      <|__     ||  ||  _  |
#|_______||___|___||___|__||_______||__||   __|
#                                       |__|   
# QARSlp Qtile + Arch Ricing System
# By: gibranlp <thisdoesnotwork@gibranlp.dev>
# MIT licence 
# 


ip addr show | awk '/inet.*brd/{print $NF; exit}' | tee ~/.config/qtile/actnet &
setxkbmap -layout us -variant intl &
pywalfox update &
/opt/bin/telwal --wal &
killall dunst &
if [ -d "~/.config/dunst/" ];  then
    cp ~/.cache/wal/dunstrc ~/.config/dunst/dunstrc &
  else
    mkdir -p ~/.config/dunst/ &
    cp ~/.cache/wal/dunstrc ~/.config/dunst/dunstrc &
 fi
