#!/usr/bin/env bash
# _______  _______  ______  _______  __        
#|       ||   _   ||   __ \|     __||  |.-----.
#|   -  _||       ||      <|__     ||  ||  _  |
#|_______||___|___||___|__||_______||__||   __|
#                                       |__|   
# QARSlp Qtile + Arch Ricing System
# By: gibranlp <thisdoesnotwork@gibranlp.dev>
# MIT licence 
#

xrandr --output HDMI-0 --mode 2560x1080 --primary --output VGA-0 --mode 1366x768 --left-of HDMI-0 &
picom --config ~/.config/picom/picom.conf &
/usr/local/bin/wvis &
#setxkbmap -layout us -variant intl &
setxkbmap -layout latam &
pywalfox update &
killall dunst &
spicetify update &
numlockx on &
nextcloud &
kdeconnect-indicator &
blueman-tray &
#nbfc config --apply "Acer Aspire E5-575G"
wal -R -q &

