#!/usr/bin/env bash
# _______  _______  ______  _______  __        
#|       ||   _   ||   __ \|     __||  |.-----.
#|   -  _||       ||      <|__     ||  ||  _  |
#|_______||___|___||___|__||_______||__||   __|
#                                       |__|   
# QARSlp Qtile + Arch Ricing System
# By: gibranlp <thisdoesnotwork@gibranlp.dev>
# MIT licence 
#
ip addr show | awk '/inet.*brd/{print $NF; exit}' | tee ~/.config/qtile/actnet &
setxkbmap -layout us -variant intl &
picom --config ~/.config/qtile/picom.conf &
numlockx on &
nextcloud &
wvis &
kdeconnect-indicator &
blueman-tray &
xrandr --output DisplayPort-1 --primary --mode 2560x1080 &
xrandr --output HDMI-0 --mode 1920x1080 --right-of DisplayPort-1 &
wal -R -q &


