#!/usr/bin/env bash
# _______  _______  ______  _______  __        
#|       ||   _   ||   __ \|     __||  |.-----.
#|   -  _||       ||      <|__     ||  ||  _  |
#|_______||___|___||___|__||_______||__||   __|
#                                       |__|   
# QARSlp Qtile + Arch Ricing System
# By: gibranlp <thisdoesnotwork@gibranlp.dev>
# MIT licence 
#
dir="${HOME}"'/Pictures/wallPapers' # Wallpapers Directory
backend="$1" # Argument for backend to use
rand_wall (){
  file=`/bin/ls -1 "$dir" | sort --random-sort | head -1` # Select random file on directory
  path=`readlink --canonicalize "$dir/$file"` # Converts to full path
  echo "${path}" | tee ~/.config/qtile/current_wallpaper
  wal -i "${path}" -q --backend "${backend}" # Wal sets wallpaper and genates new color scheme 
  qtile-cmd -o cmd -f restart # Restarts Qtile
}
rand_wall &
