#!/usr/bin/env bash
# _______  _______  ______  _______  __        
#|       ||   _   ||   __ \|     __||  |.-----.
#|   -  _||       ||      <|__     ||  ||  _  |
#|_______||___|___||___|__||_______||__||   __|
#                                       |__|   
# QARSlp Qtile + Arch Ricing System
# By: gibranlp <thisdoesnotwork@gibranlp.dev>
# MIT licence 
#
path="`cat "${HOME}"/.config/qtile/current_wallpaper`"
backend="$1" # Argument for backend to use
rand_wall (){
  wal -i "${path}" -q -l --backend "${backend}" # Wal sets wallpaper and genates new color scheme 
  qtile cmd-obj -o cmd -f restart # Restarts Qtile
  wal -R
}
rand_wall &

  