#!/usr/bin/env bash
# _______  _______  ______  _______  __        
#|       ||   _   ||   __ \|     __||  |.-----.
#|   -  _||       ||      <|__     ||  ||  _  |
#|_______||___|___||___|__||_______||__||   __|
#                                       |__|   
# QARSlp Qtile + Arch Ricing System
# By: gibranlp <thisdoesnotwork@gibranlp.dev>
# MIT licence 
# 
cp -r  ~/QARSlp/dotfiles/.[^.]* ~/
cp -r  ~/QARSlp/dotfiles/shortc.conf ~/
sudo cp -r  ~/QARSlp/scripts/* /opt/bin
sudo cp -r  ~/QARSlp/widgets/*  /opt/bin
sudo cp -r  ~/.cache/wal /root/.cache/
sudo cp -r  ~/QARSlp/dotfiles/.config/rofi/* /root/.config/rofi/
sudo cp -r  ~/QARSlp/dotfiles/themes/QARSlp /usr/share/sddm/themes/
sudo cp  ~/QARSlp/dotfiles/sddm.conf /etc/sddm.conf
