#!/usr/bin/env bash
# _______  _______  ______  _______  __        
#|       ||   _   ||   __ \|     __||  |.-----.
#|   -  _||       ||      <|__     ||  ||  _  |
#|_______||___|___||___|__||_______||__||   __|
#                                       |__|   
# QARSlp Qtile + Arch Ricing System
# By: gibranlp <thisdoesnotwork@gibranlp.dev>
# MIT licence 
# 
function i_files(){
  cp -r  ~/QARSlp/dotfiles/.[^.]* ~/
  cp -r  ~/QARSlp/dotfiles/shortc.conf ~/
  cp -r ~/QARSlp/wallPapers ~/Pictures
  sudo cp -r  ~/.cache/wal /root/.cache/
  sudo cp ~/QARSlp/dotfiles/lightdm/lightdm-gtk-greeter.conf /etc/lightdm/
  ln -s ~/.config/qtile/themes/qarslp.py  ~/.config/qtile/theme.py
  
  if [ -d "/opt/bin" ];  then
    sudo cp -r  ~/QARSlp/scripts/* /opt/bin &
    sudo cp -r  ~/QARSlp/widgets/* /opt/bin &
  else
    sudo mkdir /opt/bin &
    sudo cp -r  ~/QARSlp/scripts/* /opt/bin &
    sudo cp -r  ~/QARSlp/widgets/* /opt/bin &
 fi
  if [ -d "/root/.config/rofi" ]; then
    sudo cp -r  ~/QARSlp/dotfiles/.config/rofi/* /root/.config/rofi/ &
  else
    sudo mkdir -p /root/.config/rofi &
    sudo cp -r  ~/QARSlp/dotfiles/.config/rofi/* /root/.config/rofi/ &
fi
if [ -d "/root/.themes/FlatColor" ]; then
    sudo cp -r  ~/QARSlp/dotfiles/.themes/FlatColor/* /root/.themes/FlatColor/ &
  else
    sudo mkdir -p /root/.themes/FlatColor &
    sudo cp -r  ~/QARSlp/dotfiles/.themes/FlatColor/* /root/.themes/FlatColor/ &
fi

}

i_files

